"""Deterministic BYOK probe scripts for contested registry facts (V1.6.0-b).

When the reviewed registry records conflicting evidence for a fact that is
empirically testable (for example whether adaptive thinking can be disabled
for a model on one platform, where the provider docs and the platform model
card disagree), the toolkit emits a minimal probe script under
`output/probes/`. Same contract as the generated contract test: emitted
deterministically, never executed by the toolkit, run by the user with their
own credentials, and its result recorded with `record_observation` as a
RUN-SCOPED observation. An observation never mutates the registry; promoting
one is an explicit `propose_registry_update` with the observation as
evidence.

Provider-specific request shapes live only here. A contested fact or target
operation without a known probe shape produces no probe rather than a
misleading one.
"""

from __future__ import annotations

import json
import re
from typing import Any

from llm_migrate.core.models import InvocationMigrationSpec, MigrationUnknown

PROBES_DIR = "output/probes"

# (parameter, aspect) of a contested field path -> the request setting that
# exercises it, per target SDK operation family.
_SETTINGS: dict[tuple[str, str], dict[str, Any]] = {
    ("adaptive_thinking", "disable_supported"): {"thinking": {"type": "disabled"}},
}
_SUPPORTED_OPERATIONS = {("boto3", "converse"), ("anthropic", "messages.create")}


def contested_setting(field_path: str) -> dict[str, Any] | None:
    """The request setting that exercises a contested `...parameters.<p>.<aspect>`."""
    match = re.search(r"(?:^|\.)parameters\.([^.]+)\.([^.]+)$", field_path)
    if match is None:
        return None
    return _SETTINGS.get((match.group(1), match.group(2)))


def probe_supported(spec: InvocationMigrationSpec | None, field_path: str) -> bool:
    """Whether a probe can be emitted for this contested fact and target call."""
    if spec is None or contested_setting(field_path) is None:
        return False
    return (spec.target.sdk, spec.target.operation) in _SUPPORTED_OPERATIONS


def probe_relative_path(field_path: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", field_path.casefold()).strip("_")
    return f"{PROBES_DIR}/probe_{slug}.py"


def render_probe(
    spec: InvocationMigrationSpec,
    unknown: MigrationUnknown,
    *,
    model_id: str,
    run_dir: str,
) -> str | None:
    """The probe script for one contested-evidence unknown, or None."""
    field_path = str((unknown.data or {}).get("field_path", ""))
    setting = contested_setting(field_path)
    target = spec.target
    if setting is None or (target.sdk, target.operation) not in _SUPPORTED_OPERATIONS:
        return None
    statements = [str(item) for item in (unknown.data or {}).get("statements", [])]
    record_call = (
        f"record_observation(run_dir={run_dir!r}, subject={unknown.id!r}, "
        'outcome="<ACCEPTED or REJECTED, as printed>", evidence="<the printed line>")'
    )
    if (target.sdk, target.operation) == ("boto3", "converse"):
        call_lines = [
            "    import boto3",
            "",
            '    client = boto3.client("bedrock-runtime")',
            "    response = client.converse(",
            "        modelId=MODEL_ID,",
            '        messages=[{"role": "user", "content": [{"text": PROMPT}]}],',
            '        inferenceConfig={"maxTokens": 64},',
            "        additionalModelRequestFields=CONTESTED_SETTING,",
            "    )",
            '    blocks = response["output"]["message"]["content"]',
            '    reasoning = any("reasoningContent" in block for block in blocks)',
            '    stop = response.get("stopReason")',
            '    return f"stopReason={stop}; reasoning_returned={reasoning}"',
        ]
    else:
        call_lines = [
            "    import anthropic",
            "",
            "    client = anthropic.Anthropic()",
            "    response = client.messages.create(",
            "        model=MODEL_ID,",
            "        max_tokens=64,",
            '        messages=[{"role": "user", "content": PROMPT}],',
            "        **CONTESTED_SETTING,",
            "    )",
            '    reasoning = any(block.type == "thinking" for block in response.content)',
            '    return f"stop_reason={response.stop_reason}; reasoning_returned={reasoning}"',
        ]
    lines = [
        '"""Generated by llm-migrate: probe for a contested registry fact (review first).',
        "",
        f"Contested fact: {field_path}",
        *(f"- {statement}" for statement in statements),
        "",
        f"Sends ONE minimal request to {model_id!r} on {target.platform} via",
        f"{target.sdk} {target.operation} with the contested setting, using YOUR OWN",
        "credentials (llm-migrate never runs this and holds no credentials).",
        "Review it, run it yourself (python <this file>), then record the printed",
        "result as a run-scoped observation:",
        "",
        f"    {record_call}",
        "",
        "An observation never changes the reviewed registry.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "",
        f"MODEL_ID = {model_id!r}",
        f"CONTESTED_SETTING = json.loads({json.dumps(setting, sort_keys=True)!r})",
        'PROMPT = "Reply with the single word OK."',
        "",
        "",
        "def probe() -> str:",
        *call_lines,
        "",
        "",
        'if __name__ == "__main__":',
        "    try:",
        '        print("ACCEPTED:", probe())',
        "    except Exception as exc:  # the provider's rejection is the observation",
        '        print("REJECTED:", type(exc).__name__, exc)',
        "",
    ]
    return "\n".join(lines)
