"""Deterministic contract-test deliverable for the target invocation.

The toolkit never executes application code, provider calls, or tests itself
(local-first, review-only, no project-owned credentials). What it CAN do
deterministically is *emit* a mocked request-shape test from the prepared
invocation representation: the user wires `build_request()` to their adapted
application's request construction and runs it themselves. Supported
invocation mappings only — an unsupported or unknown target configuration
produces no test rather than a misleading one.
"""

from __future__ import annotations

from llm_migrate.core.models import CompatibilityState, InvocationMigrationSpec
from llm_migrate.core.workspace import (
    MigrationRunConfig,
    effective_target_id,
    source_spellings,
    target_spellings,
)

CONTRACT_TEST_RELATIVE_PATH = "output/validation/test_target_invocation.py"


def render_contract_test(config: MigrationRunConfig, spec: InvocationMigrationSpec) -> str | None:
    """The generated request-shape test, or None for unsupported mappings."""
    configuration = spec.configuration_migration
    if configuration is not None and configuration.state in {
        CompatibilityState.UNSUPPORTED,
        CompatibilityState.UNKNOWN,
    }:
        return None
    target = spec.target
    expected_model_id = effective_target_id(config)
    forbidden = sorted(
        {
            spelling
            for spelling in source_spellings(config)
            if spelling not in set(target_spellings(config))
        }
        | (
            {config.target_model_id}
            if config.target_invocation_requires_selector
            and config.target_model_id != expected_model_id
            else set()
        )
    )
    parameter_lines = [
        f"    {mapping.target_name!r}: {mapping.value!r},"
        for mapping in sorted(spec.parameter_mappings, key=lambda item: item.source_name)
        if mapping.target_name
        and mapping.value is not None
        and mapping.state
        in {CompatibilityState.DIRECTLY_COMPATIBLE, CompatibilityState.MECHANICALLY_CONVERTIBLE}
    ]
    container_note = (
        f"inside the {target.parameter_container!r} container"
        if target.parameter_container
        else "at the top level of the request"
    )
    lines = [
        '"""Generated by llm-migrate: target invocation contract test (review first).',
        "",
        "Asserts the request SHAPE the migrated application must produce for",
        f"{config.target.model} on {target.platform} via "
        f"{target.sdk}.{target.client}.{target.operation}.",
        "",
        "Wire `build_request()` to your application's request construction — return",
        f"the exact kwargs your code passes to {target.client}.{target.operation}",
        "(for example by extracting the call arguments into a helper, or capturing",
        "them with unittest.mock in your own test). llm-migrate emitted this file",
        "deterministically and never executes your application itself; run it with",
        "pytest yourself, then record the outcome with record_validation_disposition",
        '(method "generated_tests").',
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "from typing import Any",
        "",
        f"EXPECTED_MODEL_FIELD = {target.model_field!r}",
        f"EXPECTED_MODEL_ID = {expected_model_id!r}",
        f"FORBIDDEN_MODEL_IDS = {forbidden!r}",
        f"EXPECTED_OPERATION = {target.operation!r}",
        f"EXPECTED_MESSAGE_FIELD = {target.message_field!r}",
        f"PARAMETER_CONTAINER = {target.parameter_container!r}",
        "# Statically mapped parameter values (" + container_note + "):",
        "EXPECTED_PARAMETERS: dict[str, Any] = {",
        *parameter_lines,
        "}",
        "",
        "",
        "def build_request() -> dict[str, Any]:",
        '    """Return the kwargs your adapted application passes to the target call."""',
        "    raise NotImplementedError(",
        '        "wire this to your application\'s request construction before running"',
        "    )",
        "",
        "",
        "def _parameters(request: dict[str, Any]) -> dict[str, Any]:",
        "    if PARAMETER_CONTAINER:",
        "        return dict(request.get(PARAMETER_CONTAINER) or {})",
        "    return request",
        "",
        "",
        "def test_target_invocation_request_shape() -> None:",
        "    request = build_request()",
        "    assert request.get(EXPECTED_MODEL_FIELD) == EXPECTED_MODEL_ID, (",
        '        f"the request must invoke {EXPECTED_MODEL_ID!r} through "',
        '        f"{EXPECTED_MODEL_FIELD!r}, got {request.get(EXPECTED_MODEL_FIELD)!r}"',
        "    )",
        "    serialized = json.dumps(request, default=str, sort_keys=True)",
        "    for forbidden_id in FORBIDDEN_MODEL_IDS:",
        "        assert (",
        "            request.get(EXPECTED_MODEL_FIELD) != forbidden_id",
        '        ), f"forbidden model id {forbidden_id!r} used for invocation"',
        "        assert forbidden_id not in serialized or forbidden_id in EXPECTED_MODEL_ID, (",
        '            f"the request still references {forbidden_id!r}"',
        "        )",
        "    assert EXPECTED_MESSAGE_FIELD in request, (",
        '        f"the request must carry its content through {EXPECTED_MESSAGE_FIELD!r}"',
        "    )",
        "    parameters = _parameters(request)",
        "    for name, value in EXPECTED_PARAMETERS.items():",
        "        assert parameters.get(name) == value, (",
        '            f"parameter {name!r} must be {value!r}, got {parameters.get(name)!r}"',
        "        )",
        "",
    ]
    return "\n".join(lines)
